version: "1.0" 
name: myapp
services:
  shop-app:
    image: typoerror/online-shopping-app:latest
    ports:
      - "80:80" 
    restart: always
    networks:
      - shop-app
networks:
  shop-app:
    driver: bridge
